import type { ProjectAnalyticsConstants } from "./types";

export const takeBringAnalyticsConstants: ProjectAnalyticsConstants = {
  serviceAnalytics: [
    {
      id: "courier",
      label: "Courier",
      paths: ["/kuriertransporte", "/courier-transport", "/transport-curier"],
      formKeys: ["service-lead-courier"],
    },
    {
      id: "freight",
      label: "Freight",
      paths: ["/spedition-lkw", "/freight-forwarding", "/expeditie-camion"],
      formKeys: ["service-lead-freight"],
    },
    {
      id: "refrigerated",
      label: "Refrigerated",
      paths: [
        "/kuehltransporte",
        "/refrigerated-transport",
        "/transport-frigorific",
      ],
      formKeys: ["service-lead-refrigerated"],
    },
    {
      id: "regularTours",
      label: "Regular tours",
      paths: ["/feste-routen", "/regular-tours", "/tururi-regulate"],
      formKeys: ["service-lead-regularTours"],
    },
    {
      id: "international",
      label: "International",
      paths: [
        "/internationaler-versand",
        "/international-shipping",
        "/transport-international",
      ],
      formKeys: ["service-lead-international"],
    },
  ],
  ctaLabels: {
    "book-express": "Book Express",
    calculator: "Calculate price",
    call: "Call",
    whatsapp: "WhatsApp",
    "floating-call": "Floating Call",
    "floating-whatsapp": "Floating WhatsApp",
    track: "Track shipment",
    newsletter: "Newsletter",
    contact: "Contact form",
  },
  localeLabels: {
    ro: "Romanian",
    de: "German",
    en: "English",
  },
  pageLabels: {
    "/": "Homepage",
    "/kontakt": "Contact",
    "/contact": "Contact",
    "/blog": "Blog",
    "/branchen": "Industries",
    "/industries": "Industries",
    "/industrii": "Industries",
    "/tracking": "Tracking",
    "/ueber-uns": "About",
    "/about-us": "About",
    "/despre-noi": "About",
    "/kuriertransporte": "Courier transport",
    "/courier-transport": "Courier transport",
    "/transport-curier": "Courier transport",
    "/spedition-lkw": "Freight forwarding",
    "/freight-forwarding": "Freight forwarding",
    "/expeditie-camion": "Freight forwarding",
    "/kuehltransporte": "Refrigerated transport",
    "/refrigerated-transport": "Refrigerated transport",
    "/transport-frigorific": "Refrigerated transport",
    "/feste-routen": "Fixed routes",
    "/regular-tours": "Fixed routes",
    "/tururi-regulate": "Fixed routes",
    "/internationaler-versand": "International shipping",
    "/international-shipping": "International shipping",
    "/transport-international": "International shipping",
  },
};
